apiVersion: apps/v1 
kind: Deployment
metadata:
  name: doom-deploy
spec:
  selector:
    matchLabels:
      app: doom-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: doom-deploy
    spec:
      containers:
      - name: doom-deploy
        image: nzregularit/doombox
        ports:
        - containerPort: 443