apiVersion: apps/v1 
kind: Deployment
metadata:
  name: doombox
  namespace: doombox-demo
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: doombox
  replicas: 3
  template:
    metadata:
      labels:
        app: doombox
    spec:
      containers:
      - name: doombox
        image: nzregularit/doombox
        ports:
        - containerPort: 443