apiVersion: v1
kind: Service
metadata:
  name: doom-service
  labels:
    app: doom-deployment
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: doom-deployment
  type: LoadBalancer