apiVersion: v1
kind: Service
metadata:
  name: doom-deploy
  labels:
    name: doom-deploy
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: doom-deploy
  type: LoadBalancer