apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: doombox
  namespace: doombox-demo
spec:
  releaseName: doombox
  chart:
    git: https://github.com/nzRegularIT/doombox
    path: charts
    ref: master
